environment:
  nodejs_version: "9"
cache:
  - '%LOCALAPPDATA%\Yarn -> appveyor.yml'
  - node_modules -> yarn.lock

install:
  - ps: Install-Product node $env:nodejs_version x64
  - git submodule sync
  - git submodule update --init --recursive
  - git config --global user.email "dxcli@example.com"
  - git config --global user.name "dxcli"
  - yarn
test_script:
  - >
    npx nps
      lint
      test.base.everything
      test.base.mocha
      test.base.plain
      test.base.semantic-release
      test.base.typescript
      test.single.everything
      test.single.mocha
      test.single.plain
      test.single.semantic-release
      test.single.typescript

after_test:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh

build: off

