---
version: 2
jobs:
  node-latest-base: &test
    docker:
      - image: node:latest
    working_directory: ~/cli
    steps:
      - checkout
      - run: ./scripts/circleci
      - run: npx nps lint
      - run: npx nps test.base
      - store_test_results: &store_test_results
          path: ~/cli/reports
  node-latest-single:
    <<: *test
    steps:
      - checkout
      - run: ./scripts/circleci
      - run: npx nps test.single
      - store_test_results: *store_test_results
  node-latest-plugin:
    <<: *test
    steps:
      - checkout
      - run: ./scripts/circleci
      - run: npx nps test.plugin
      - store_test_results: *store_test_results
  node-latest-multi:
    <<: *test
    steps:
      - checkout
      - run: ./scripts/circleci
      - run: npx nps test.multi
      - store_test_results: *store_test_results
  node-8-base:
    <<: *test
    docker:
      - image: node:8
    steps:
      - checkout
      - run: ./scripts/circleci
      - run: npx nps lint
      - run: npx nps test.base
      - store_test_results: *store_test_results
  node-8-single:
    <<: *test
    docker:
      - image: node:8
    steps:
      - checkout
      - run: ./scripts/circleci
      - run: npx nps test.single
      - store_test_results: *store_test_results
  node-8-plugin:
    <<: *test
    docker:
      - image: node:8
    steps:
      - checkout
      - run: ./scripts/circleci
      - run: npx nps test.plugin
      - store_test_results: *store_test_results
  node-8-multi:
    <<: *test
    docker:
      - image: node:8
    steps:
      - checkout
      - run: ./scripts/circleci
      - run: npx nps test.multi
      - store_test_results: *store_test_results

  release:
    <<: *test
    steps:
      - add_ssh_keys
      - checkout
      - run: ./scripts/circleci
      - run: ./node_modules/.bin/nps ci.release
      - run: |
          git clone git@github.com:dxcli/create-dxcli
          cd create-dxcli
          yarn
          yarn upgrade --latest generator-dxcli
          yarn test
          VERSION=$(node -p "require('../package.json').version")
          git add package.json yarn.lock
          if ! git diff-index --quiet HEAD --; then
            git commit -m "feat: generator-dxcli@$VERSION"
            git push
          fi

workflows:
  version: 2
  "generator-dxcli":
    jobs:
      - node-latest-base
      - node-latest-single
      - node-latest-plugin
      - node-latest-multi
      - node-8-base
      - node-8-single
      - node-8-plugin
      - node-8-multi
      - release:
          context: org-global
          filters:
            branches: {only: master}
          requires:
            - node-latest-base
            - node-latest-single
            - node-latest-plugin
            - node-latest-multi
            - node-8-base
            - node-8-single
            - node-8-plugin
            - node-8-multi
