---
version: 2
jobs:
  node-latest: &test
    docker:
      - image: node:latest
    working_directory: ~/cli
    steps:
      - checkout
      - restore_cache: &restore_cache
          keys:
            - v0-yarn-{{ .Environment.CIRCLE_JOB }}-{{checksum "scripts/circleci"}}-{{checksum ".circleci/config.yml"}}-{{ .Branch }}-{{checksum "yarn.lock"}}
            - v0-yarn-{{ .Environment.CIRCLE_JOB }}-{{checksum "scripts/circleci"}}-{{checksum ".circleci/config.yml"}}-{{ .Branch }}-
            - v0-yarn-{{ .Environment.CIRCLE_JOB }}-{{checksum "scripts/circleci"}}-{{checksum ".circleci/config.yml"}}-master-
      - run: ./scripts/circleci test
      - store_test_results:
          path: ~/cli/reports
      - save_cache: &save_cache
          key: v0-yarn-{{ .Environment.CIRCLE_JOB }}-{{checksum "scripts/circleci"}}-{{checksum ".circleci/config.yml"}}-{{ .Branch }}-{{checksum "yarn.lock"}}
          paths:
            - ~/cli/node_modules
            - /usr/local/share/.cache/yarn
            - /usr/local/share/.config/yarn
  node-8:
    <<: *test
    docker:
      - image: node:8
  release:
    <<: *test
    steps:
      - add_ssh_keys
      - checkout
      - restore_cache: *restore_cache
      - run: ./scripts/circleci release
      - run: |
          git clone git@github.com:dxcli/create-dxcli
          cd create-dxcli
          yarn
          yarn upgrade --latest generator-dxcli
          yarn test
          if ! git diff-index --quiet HEAD --; then
            git add package.json yarn.lock
            git commit -m "feat: updated generator-dxcli"
            git push
          fi

      - save_cache: *save_cache

workflows:
  version: 2
  "generator-dxcli":
    jobs:
      - node-latest
      - node-8
      - release:
          context: org-global
          filters:
            branches: {only: master}
          requires:
            - node-latest
            - node-8
