---
version: 2
jobs:
  node-latest-base: &test
    docker:
      - image: node:latest
    working_directory: ~/cli
    steps:
      - checkout
      - restore_cache: &restore_cache
          keys:
            - v0-yarn-{{ .Environment.CIRCLE_JOB }}-{{checksum "scripts/circleci"}}-{{checksum ".circleci/config.yml"}}-{{ .Branch }}-{{checksum "yarn.lock"}}
            - v0-yarn-{{ .Environment.CIRCLE_JOB }}-{{checksum "scripts/circleci"}}-{{checksum ".circleci/config.yml"}}-{{ .Branch }}-
            - v0-yarn-{{ .Environment.CIRCLE_JOB }}-{{checksum "scripts/circleci"}}-{{checksum ".circleci/config.yml"}}-master-
      - run: ./scripts/circleci test
      - run: npx nps lint
      - run: npx nps test.base
      - store_test_results: &store_test_results
          path: ~/cli/reports
      - save_cache: &save_cache
          key: v0-yarn-{{ .Environment.CIRCLE_JOB }}-{{checksum "scripts/circleci"}}-{{checksum ".circleci/config.yml"}}-{{ .Branch }}-{{checksum "yarn.lock"}}
          paths:
            - ~/cli/node_modules
            - /usr/local/share/.cache/yarn
            - /usr/local/share/.config/yarn
  node-latest-single:
    <<: *test
    steps:
      - checkout
      - restore_cache: *restore_cache
      - run: ./scripts/circleci test
      - run: npx nps test.single
      - store_test_results: *store_test_results
      - save_cache: *save_cache
  node-8-base:
    <<: *test
    docker:
      - image: node:8
    steps:
      - checkout
      - restore_cache: *restore_cache
      - run: ./scripts/circleci test
      - run: npx nps lint
      - run: npx nps test.base
      - store_test_results: *store_test_results
      - save_cache: *save_cache
  node-8-single:
    <<: *test
    docker:
      - image: node:8
    steps:
      - checkout
      - restore_cache: *restore_cache
      - run: ./scripts/circleci test
      - run: npx nps test.single
      - store_test_results: *store_test_results
      - save_cache: *save_cache

  release:
    <<: *test
    steps:
      - add_ssh_keys
      - checkout
      - restore_cache: *restore_cache
      - run: ./node_modules/.bin/nps ci.release
      - run: |
          git clone git@github.com:dxcli/create-dxcli
          cd create-dxcli
          yarn
          yarn upgrade --latest generator-dxcli
          yarn test
          if ! git diff-index --quiet HEAD --; then
            VERSION=$(node -p "require('../package.json').version")
            git add package.json yarn.lock
            git commit -m "feat: generator-dxcli@$VERSION"
            git push
          fi

      - save_cache: *save_cache

workflows:
  version: 2
  "generator-dxcli":
    jobs:
      - node-latest-base
      - node-latest-single
      - node-8-base
      - node-8-single
      - release:
          context: org-global
          filters:
            branches: {only: master}
          requires:
            - node-latest-base
            - node-latest-single
            - node-8-base
            - node-8-single
